export const statuses: Record<string, string> = {
  DRAFT: '草稿',
  PENDING_APPROVAL: '待审批',
  APPROVED: '已批准',
  REJECTED: '已驳回',
  CANCELLED: '已取消',
  ORDERED: '待收货',
  PARTIAL: '部分入库',
  COMPLETED: '已完成',
  ACTIVE: '在职',
  ON_LEAVE: '休假',
  TERMINATED: '已离职',
  ENABLED: '正常',
  PENDING: '待首次登录',
  LOCKED: '已锁定',
  DISABLED: '已停用',
  NONE: '未开通',
  INACTIVE: '停用',
  INBOUND: '采购入库',
  OUTBOUND: '出库',
  ADJUSTMENT: '库存调整',
  LOW: '库存预警',
  OK: '正常',
}
export const statusText = (value: string) => statuses[value] || value
