"""add filed

Revision ID: e5d33124f081
Revises: 6b6f4ee3ae14
Create Date: 2026-09-15 17:28:52.285389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d33124f081'
down_revision = '6b6f4ee3ae14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled_reason', sa.String(length=255), nullable=True))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('hire_date', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('hire_date')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('position')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('disabled_reason')

    # ### end Alembic commands ###
